NumPy is a powerful library in Python that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. When you create a NumPy array, you're essentially creating a data structure that can hold elements of the same data type arranged in a grid, either as a vector, a matrix, or a higher-dimensional array.


You can perform various operations on this array, such as slicing, reshaping, arithmetic operations, and much more. The key advantage of using NumPy arrays is their efficiency and the wide range of mathematical functions available for array manipulation.







In [1]:
import numpy as np

In [2]:
my_list=[1,2,3,4]

In [3]:
np.array(my_list)

array([1, 2, 3, 4])

Note: with np.arrange() you can automatically make the np.array

In [4]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

You can also set the steps from start to end

In [5]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

Note: Np.zeros() return matrix with only the zeros

In [6]:
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

The same goes for np.ones()

In [8]:
np.ones(3)

array([1., 1., 1.])

Note: np.linspace() would get the start and end and the number of the points should be between start and end.

In [9]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

np.eye(n) would return the matrix, n X n, **all** zeros with the non-zero diagnal.

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

the .rand() would retun you some random numbers between 0 and 1

In [11]:
np.random.rand(3)

array([0.77586715, 0.23851101, 0.26349314])

You can also get a matrix n X m

In [12]:
np.random.rand(3,5)

array([[0.4131496 , 0.17055005, 0.46554565, 0.1924147 , 0.67903375],
       [0.27702493, 0.85785112, 0.62695261, 0.09918758, 0.95242727],
       [0.07079158, 0.44173784, 0.38651708, 0.40463015, 0.16521312]])

for the .randn() you get some random data with 0 mean and 1 variance

In [13]:
np.random.randn(5,5)

array([[-0.57314089,  0.70252289,  0.64088198,  0.82370548,  0.9555339 ],
       [ 1.05036234,  1.01770937,  1.40128812, -0.16495074, -0.83568801],
       [ 1.10094447, -0.21613898, -1.16975691, -0.3240844 ,  0.26658941],
       [-0.05320542,  0.10262351, -0.69584076,  1.07674472,  1.54326165],
       [ 0.74684106, -1.06168058,  0.22346681, -1.13482179,  0.65426249]])

the ,randint(a,b) return intiger random points amon a and b

In [14]:
np.random.randint(2,100,5)

array([10, 87, 43, 36, 91])

In [15]:
np.random.randint(2,100,(2,3))

array([[14, 91, 79],
       [20, 73, 36]])

Note: with .seed() you can fix the random point that you get every time

In [16]:
np.random.seed(42)
np.random.randint(100,140)

138

Note: .reshape() would reshape the array.

In [17]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

.max() and .min() would return max and min

In [19]:
arr.max()

24

In [20]:
arr.reshape(5,5).max()

24

argmax() would return the location of the max element

In [21]:
arr.argmax()

24

note: dtype would retun the type of the data

In [22]:
arr.dtype

dtype('int64')

**indexing and selection**

In [23]:
arr=np.arange(0,15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
arr[8]

8

In [25]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [26]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [27]:
arr[6:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

: means every thing

In [28]:
arr2=arr[:]
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Note: in numpy you can assign new amount to the data. In the normal list you cannot do this

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
arr[5:11]=100
arr

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100, 100,  11,  12,
        13,  14])

in numpy you can also do the slicing

In [31]:
arr=np.arange(1,14)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [32]:
sliced_arr=arr[1:5]
sliced_arr

array([2, 3, 4, 5])

In [33]:
arr2d=np.array([[1,2,3],[5,6,3],[1,5,6]])
arr2d

array([[1, 2, 3],
       [5, 6, 3],
       [1, 5, 6]])

note: .shape would return the number of the rows and columns of the array

In [34]:
arr2d.shape

(3, 3)

we can index the rows and columns with of the arr2d with the following codes

In [35]:
arr2d[0,:]

array([1, 2, 3])

In [36]:
arr2d[:,1]

array([2, 6, 5])

with the following code we can get all the rows and columns until sepcified row or column

In [37]:
arr2d[:2,:]

array([[1, 2, 3],
       [5, 6, 3]])

In [38]:
arr2d[:,:2]

array([[1, 2],
       [5, 6],
       [1, 5]])

In [39]:
arr2d[:1,2:]

array([[3]])

Note: in arr2d if I want the element on second row and second column what should I do?

In [40]:
arr2d[1][1]

6

OR

In [41]:
arr2d[1,1]

6

in numpy you can also have the conditional selection

In [42]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

which part of my arr is greator than 4?

In [43]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

we can use this feature to filter the array

In [44]:
bool=arr>4

In [45]:
arr[bool]

array([ 5,  6,  7,  8,  9, 10])

**Operations**

Note: Numpy perform operations on element on element bases.

In [48]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr+5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [51]:
arr/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        , 2.33333333, 2.66666667, 3.        ])

In [53]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [54]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

note: .sum() would sum up all the numbers in the array.

In [55]:
arr.sum()

45

In [56]:
arr.mean()

5.0

In [57]:
arr.max()

9

In [58]:
arr.min()

1

Note: .var() is the variance function.

In [59]:
arr.var()

6.666666666666667

Note: .std() would calculate the stadard variation.

In [60]:
arr.std()

2.581988897471611

In [64]:
arr2d=np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
arr2d.sum()

300

Note: rows ----> axis=0
columns -----> axis=1
when we say arr2d.sum(axis=0) it means that do the operation ACROSS the rows (which means for every column).

In [66]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])